name: madari_engine
description: Madari engine for the madari app
version: 1.0.10
repository: https://github.com/madari-media/engine

environment:
  sdk: ^3.6.0

dependencies:
  json_annotation: ^4.9.0
  pocketbase: ^0.19.1
  logging: ^1.3.0
  http: ^1.3.0
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
